services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claim-thunjai
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
