import type { Metadata, Viewport } from "next";
import "./globals.css";
import { LangProvider } from "@/lib/LangContext";
import { Header } from "@/components/Header";
import PortalLayout from "@/components/PortalLayout";
import { ServiceWorkerRegistrar } from "@/components/ServiceWorkerRegistrar";

export const metadata: Metadata = {
  title: "ClaimThunJai · AI Damage Detection for Insurance",
  description: "Claude-powered car damage detection for insurance companies. B2B2C.",
  // The manifest itself is generated by src/app/manifest.ts and linked automatically.
  appleWebApp: {
    capable: true,
    title: "ClaimThunJai",
    // The app renders its own dark navy top bar; a translucent status bar would let
    // the page scroll underneath it on iOS.
    statusBarStyle: "default",
  },
  icons: {
    icon: [
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export const viewport: Viewport = {
  // Matches the manifest theme_color so the status bar blends into the app's top bar.
  themeColor: "#0b132a",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="th" className="h-full">
      <body className="min-h-full flex flex-col bg-white text-slate-900" suppressHydrationWarning>
        <ServiceWorkerRegistrar />
        <LangProvider>
          <Header />
          <PortalLayout>{children}</PortalLayout>
        </LangProvider>
      </body>
    </html>
  );
}
